import type { BankDirection, BankMode, BankRule, BankTransaction, RawBankTransaction } from './types';
import type { Customer } from '@/lib/customers/types';
import type { Invoice, Expense } from '@/lib/data/types';

const norm=(s:string)=>s.toLowerCase().replace(/[^a-z0-9@._ -]/gi,' ').replace(/\s+/g,' ').trim();
const paise=(n:number)=>BigInt(Math.round(n*100));
export const moneyFromText=(raw:string):bigint|null=>{const s=raw.replace(/,/g,'').replace(/₹/g,'').trim(); const m=s.match(/-?\d+(?:\.\d{1,2})?/); return m?paise(Number(m[0])):null};
export function parseDate(value:string){const s=value.trim(); const dmy=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})$/); if(dmy){let y=Number(dmy[3]); if(y<100)y+=2000; const d=new Date(Date.UTC(y,Number(dmy[2])-1,Number(dmy[1]))); return Number.isNaN(d.getTime())?null:d.toISOString().slice(0,10);} const iso=new Date(s); return Number.isNaN(iso.getTime())?null:iso.toISOString().slice(0,10);}
export function normaliseMerchant(narration:string){let s=norm(narration); s=s.replace(/upi\/(?:dr|cr)\/?/g,' ').replace(/utr[: -]?[a-z0-9-]+/g,' ').replace(/ref(?:erence)?[: -]?[a-z0-9-]+/g,' ').replace(/\d{10,}/g,' ').trim(); const parts=s.split(/\s{2,}|[|;]/).map(x=>x.trim()).filter(Boolean); return (parts[0]||s||'Unknown').replace(/\b(?:paytm|gpay|googlepay|phonepe)\b/gi,'').trim().replace(/\s+/g,' ') || 'Unknown';}
export function inferMode(narration:string):BankMode{const s=narration.toUpperCase(); if(s.includes('UPI'))return'UPI';if(s.includes('NEFT'))return'NEFT';if(s.includes('IMPS'))return'IMPS';if(s.includes('RTGS'))return'RTGS';if(s.includes('ATM'))return'ATM';if(s.includes('POS')||s.includes('CARD'))return'CARD';if(s.includes('CHQ')||s.includes('CHEQUE'))return'CHEQUE';if(s.includes('CASH DEP'))return'CASH_DEPOSIT';return'OTHER';}
export function fingerprint(tx:{date:string;amountPaise:bigint;narration:string;runningBalancePaise?:bigint}){return [tx.date,tx.amountPaise.toString(),norm(tx.narration),tx.runningBalancePaise?.toString()||''].join('|');}
export function isDuplicate(tx:RawBankTransaction, existing:RawBankTransaction[]){return !!existing.find(x=>(tx.sourceTransactionId&&x.sourceTransactionId===tx.sourceTransactionId&&x.accountId===tx.accountId)||x.fingerprint===tx.fingerprint);}
export function applyRules(tx:RawBankTransaction,rules:BankRule[]){for(const r of rules){if(!r.enabled)continue;const n=norm(tx.narration);if(r.narrationContains&&!n.includes(norm(r.narrationContains)))continue;if(r.direction&&r.direction!==tx.direction)continue;if(r.minAmountPaise!==undefined&&tx.amountPaise<r.minAmountPaise)continue;if(r.maxAmountPaise!==undefined&&tx.amountPaise>r.maxAmountPaise)continue;return{category:r.category,confidence:0.99,reason:`Rule: ${r.name}`,tag:r.tag};}return null;}
export function suggestCategory(tx:RawBankTransaction,rules:BankRule[],history:Map<string,{category:string;count:number}>,customers:Customer[],expenses:Expense[]){const ruled=applyRules(tx,rules);if(ruled)return ruled; const merchant=normaliseMerchant(tx.narration); const h=history.get(norm(merchant)); if(h)return{category:h.category,confidence:Math.min(.95,.72+h.count*.05),reason:'Previously categorised vendor'}; const n=norm(tx.narration); const keyword=n.match(/rent|salary|fuel|petrol|diesel|electric|internet|office|stationery|software|amazon|flipkart|travel|hotel|food|restaurant|gst|tds|tax|bank charge|insurance/); const map:Record<string,string>={rent:'Rent',salary:'Salaries',fuel:'Travel & Fuel',petrol:'Travel & Fuel',diesel:'Travel & Fuel',electric:'Utilities',internet:'Utilities',office:'Office Supplies',stationery:'Office Supplies',software:'Software & Subscriptions',amazon:'Office Supplies',flipkart:'Office Supplies',travel:'Travel',hotel:'Travel',food:'Meals',restaurant:'Meals',gst:'GST Payment',tds:'TDS Payment',tax:'Tax Payment','bank charge':'Bank Charges',insurance:'Insurance'}; if(keyword)return{category:map[keyword[0]]||'Other',confidence:.78,reason:'Narration keyword match'}; const customer=customers.find(c=>norm(c.displayName)===norm(merchant)||norm(c.legalName)===norm(merchant)); if(customer&&tx.direction==='CREDIT')return{category:'Sales Receipt',confidence:.82,reason:'Customer name match'}; return{category:tx.direction==='CREDIT'?'Sales Receipt':'Other',confidence:.35,reason:'Low-confidence default'};}
export function suggestInvoiceMatches(tx:RawBankTransaction,invoices:Invoice[],customers:Customer[]){if(tx.direction!=='CREDIT')return[]; const merchant=norm(normaliseMerchant(tx.narration)); return invoices.filter(i=>{if(i.status==='Draft')return false;const total=paise(i.lines.reduce((s,l)=>s+Number(l.quantity)*Number(l.unitPrice),0)+i.tax-i.discount); const amountClose=total===tx.amountPaise||Math.abs(Number(total-tx.amountPaise))<=Math.max(100,Number(total)*.05); const customer=customers.find(c=>c.id===i.customerId||norm(c.displayName)===norm(i.customer)); const name=customer&&(merchant.includes(norm(customer.displayName))||norm(customer.displayName).includes(merchant)); const days=Math.abs((new Date(tx.date).getTime()-new Date(i.dueDate).getTime())/86400000); return amountClose||!!name&&days<=15;}).slice(0,5).map(i=>i.id);}
export function detectInternalTransfer(tx:RawBankTransaction, accounts:string[]){if(tx.direction==='CREDIT'&&/self|own account|transfer to own|internal/i.test(tx.narration))return true;if(tx.direction==='DEBIT'&&/self|own account|transfer from own|internal/i.test(tx.narration))return true;return accounts.some(a=>tx.narration.includes(String(a).slice(-4)));}
export function createTransaction(raw:RawBankTransaction,rules:BankRule[],history:Map<string,{category:string;count:number}>,customers:Customer[],expenses:Expense[],invoices:Invoice[],accounts:BankTransaction['accountId'][]){const s=suggestCategory(raw,rules,history,customers,expenses);const merchant=normaliseMerchant(raw.narration);const invoiceIds=suggestInvoiceMatches(raw,invoices,customers);const internal=detectInternalTransfer(raw,accounts);return{...raw,merchant,category:internal?'Internal Transfer':s.category,confidence:internal?.99:s.confidence,suggestionReason:internal?'Likely transfer between own accounts':s.reason,invoiceIds:internal?[]:invoiceIds,status:internal?'CATEGORISED':'UNREVIEWED',business:true,tags:s.tag?[s.tag]:[],autoApplied:false} satisfies BankTransaction;}
export function agingLikeBalance(transactions:BankTransaction[]){return transactions.reduce((s,t)=>s+(t.business?(t.direction==='CREDIT'?t.amountPaise:-t.amountPaise):0n),0n);}
