import type { BankDirection, RawBankTransaction, BankSource } from './types';
import { fingerprint, moneyFromText, parseDate, inferMode } from './engine';

const clean=(v:unknown)=>String(v??'').trim();
const find=(row:Record<string,string>, names:string[])=>{const keys=Object.keys(row);const k=keys.find(x=>names.some(n=>x.toLowerCase().replace(/[^a-z]/g,'').includes(n)));return k?row[k]:''};
export function parseStatementRows(rows:Record<string,string>[],accountId:string,source:BankSource='STATEMENT_UPLOAD'){const out:RawBankTransaction[]=[];for(let i=0;i<rows.length;i++){const r=rows[i];const date=parseDate(find(r,['date','transactiondate','valuedate']));if(!date)continue;const narration=find(r,['narration','description','details','particulars','remarks']);const ref=find(r,['utr','reference','refno','transactionid','chequeno']);const debit=moneyFromText(find(r,['debit','withdrawal','dr']));const credit=moneyFromText(find(r,['credit','deposit','cr']));let amount=moneyFromText(find(r,['amount','transactionamount']));let direction:BankDirection='DEBIT';if(credit!==null){amount=credit;direction='CREDIT';}else if(debit!==null){amount=debit;direction='DEBIT';}else if(amount!==null){direction=/credit|cr|deposit|received/i.test(clean(find(r,['type','direction'])))?'CREDIT':'DEBIT';}if(!amount||amount<=0n)continue;const balance=moneyFromText(find(r,['balance','closingbalance','runningbalance']));const raw={id:`raw-${source}-${accountId}-${i}`,source,sourceTransactionId:ref||undefined,accountId,date,amountPaise:amount,direction,narration,reference:ref||undefined,mode:inferMode(narration),runningBalancePaise:balance||undefined,rawPayload:JSON.stringify(r),fingerprint:fingerprint({date,amountPaise:amount,narration,runningBalancePaise:balance||undefined}),importedAt:new Date().toISOString()};out.push(raw);}return out;}
export function parseCsv(text:string){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const parse=(line:string)=>{const cells:string[]=[];let cur='',quote=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quote&&line[i+1]==='"'){cur+='"';i++;}else quote=!quote;}else if(c===','&&!quote){cells.push(cur);cur='';}else cur+=c;}cells.push(cur);return cells;};const headers=parse(lines[0]).map(x=>x.trim());return lines.slice(1).map(l=>{const cells=parse(l);return Object.fromEntries(headers.map((h,i)=>[h,cells[i]||'']));});}
export async function parseXlsx(file:ArrayBuffer){const XLSX=await import('xlsx');const wb=XLSX.read(file,{type:'array'});const sheet=wb.Sheets[wb.SheetNames[0]];return XLSX.utils.sheet_to_json<Record<string,string>>(sheet,{defval:''});}
export async function parsePdf(file:ArrayBuffer){const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');const doc=await pdfjs.getDocument({data:new Uint8Array(file)}).promise;const rows:Record<string,string>[]=[];for(let p=1;p<=doc.numPages;p++){const page=await doc.getPage(p);const content=await page.getTextContent();const text=content.items.map((x:any)=>x.str).join(' ');const date=text.match(/\b\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}\b/)?.[0];const amounts=[...text.matchAll(/(?:₹|INR)?\s?\d[\d,]*(?:\.\d{1,2})?/g)].map(m=>m[0]).filter(x=>/\d/.test(x));if(date&&amounts.length)rows.push({Date:date,Narration:text,Amount:amounts[amounts.length-1]});}return rows;}
