'use client';
import {create} from 'zustand';
import {persist,createJSONStorage} from 'zustand/middleware';
import type {BankAccount,BankConsent,BankRule,BankState,BankTransaction,RawBankTransaction} from './types';
import {createTransaction,isDuplicate,normaliseMerchant} from './engine';
import {parseCsv,parsePdf,parseStatementRows,parseXlsx} from './parser';
import {useFinova} from '@/lib/data/store';
import {useCustomers} from '@/lib/customers/store';

const demoAccounts:BankAccount[]=[{id:'bank-hdfc-demo',bankName:'HDFC Bank',accountType:'CURRENT',maskedAccountNumber:'•••• 4821',balancePaise:28745000n,balanceDate:new Date().toISOString(),source:'SANDBOX_AA',businessUse:true,syncStatus:'CONNECTED',lastSyncedAt:new Date().toISOString(),reconciledUpTo:new Date().toISOString().slice(0,10)}];
const demoRules:BankRule[]=[{id:'r-office',name:'Office suppliers',narrationContains:'ABC OFFICE',category:'Office Supplies',enabled:true,createdAt:new Date().toISOString()}];
const demoRaw:RawBankTransaction[]=[{id:'raw-demo-1',source:'SANDBOX_AA',sourceTransactionId:'UTR-DEMO-1001',accountId:'bank-hdfc-demo',date:new Date().toISOString().slice(0,10),amountPaise:250000n,direction:'DEBIT',narration:'UPI/ABC OFFICE SUPPLIES/REF123',reference:'UTR-DEMO-1001',mode:'UPI',runningBalancePaise:28500000n,rawPayload:'{"sandbox":true}',fingerprint:'demo-1',importedAt:new Date().toISOString()},{id:'raw-demo-2',source:'SANDBOX_AA',sourceTransactionId:'UTR-DEMO-1002',accountId:'bank-hdfc-demo',date:new Date().toISOString().slice(0,10),amountPaise:1250000n,direction:'CREDIT',narration:'NEFT ACME CLIENT PAYMENT INV-1007',reference:'UTR-DEMO-1002',mode:'NEFT',runningBalancePaise:29750000n,rawPayload:'{"sandbox":true}',fingerprint:'demo-2',importedAt:new Date().toISOString()}];
export const useBank=create<BankState & {importFile:(file:File,accountId:string)=>Promise<{added:number;duplicates:number;errors:string[]}>;confirm:(id:string,patch?:Partial<BankTransaction>)=>void;ignore:(id:string)=>void;bulkConfirm:(ids:string[])=>void;addRule:(r:Omit<BankRule,'id'|'createdAt'>)=>void;createConsent:(provider:string,accountId:string)=>BankConsent;disconnect:(accountId:string)=>void;seedSandbox:()=>void;removeAccount:(id:string)=>void}>() (persist((set,get)=>({accounts:demoAccounts,consents:[],raw:demoRaw,transactions:[],rules:demoRules,scanCredits:10,premium:process.env.NEXT_PUBLIC_FINOVA_PREMIUM==='true',
  seedSandbox:()=>{if(get().transactions.length)return;const fin=useFinova.getState();const cust=useCustomers.getState().customers;const hist=new Map<string,{category:string;count:number}>();const tx=demoRaw.map(r=>createTransaction(r,get().rules,hist,cust,fin.expenses,fin.invoices,get().accounts.map(a=>a.maskedAccountNumber)));set({transactions:tx});},
  importFile:async(file,accountId)=>{const ext=file.name.toLowerCase().split('.').pop();try{let rows:Record<string,string>[]=[];if(ext==='csv'||ext==='txt')rows=parseCsv(await file.text());else if(ext==='xlsx'||ext==='xls')rows=await parseXlsx(await file.arrayBuffer());else if(ext==='pdf')rows=await parsePdf(await file.arrayBuffer());else return{added:0,duplicates:0,errors:['Unsupported file. Use CSV, Excel or PDF.']};const fin=useFinova.getState();const cust=useCustomers.getState().customers;const hist=new Map<string,{category:string;count:number}>();const existing=get().raw;let added=0,duplicates=0;const raws=parseStatementRows(rows,accountId);const txs:BankTransaction[]=[];for(const raw of raws){if(isDuplicate(raw,existing)||isDuplicate(raw,[...raws.slice(0,txs.length)])){duplicates++;continue;}raw.mode=raw.mode;const tx=createTransaction(raw,get().rules,hist,cust,fin.expenses,fin.invoices,get().accounts.map(a=>a.maskedAccountNumber));txs.push(tx);added++;}set(s=>({raw:[...txs,...s.raw],transactions:[...txs,...s.transactions],scanCredits:Math.max(0,s.scanCredits-added)}));return{added,duplicates,errors:[]};}catch(e){return{added:0,duplicates:0,errors:[e instanceof Error?e.message:'Statement parsing failed']};}},
  confirm:(id,patch)=>set(s=>{const t=s.transactions.find(x=>x.id===id);if(!t)return s;const next={...t,...patch,status:patch?.status||'CATEGORISED',reviewAt:new Date().toISOString()};const history=new Map<string,{category:string;count:number}>();const merchant=normaliseMerchant(next.narration);if(next.category)history.set(merchant,{category:next.category,count:1});return{transactions:s.transactions.map(x=>x.id===id?next:x)};}),
  ignore:id=>set(s=>({transactions:s.transactions.map(x=>x.id===id?{...x,status:'IGNORED',reviewAt:new Date().toISOString()}:x)})),
  bulkConfirm:ids=>set(s=>({transactions:s.transactions.map(x=>ids.includes(x.id)&&x.status==='UNREVIEWED'?{...x,status:'CATEGORISED',reviewAt:new Date().toISOString()}:x)})),
  addRule:r=>set(s=>({rules:[{...r,id:crypto.randomUUID(),createdAt:new Date().toISOString()},...s.rules]})),
  createConsent:(provider,accountId)=>{const now=new Date();const c:BankConsent={id:crypto.randomUUID(),accountIds:[accountId],provider,status:'ACTIVE',purpose:'Finova bookkeeping and cash-flow reconciliation',fiTypes:['DEPOSIT'],startDate:new Date(now.getFullYear()-1,now.getMonth(),now.getDate()).toISOString(),endDate:now.toISOString(),createdAt:now.toISOString(),expiresAt:new Date(now.getTime()+90*86400000).toISOString()};set(s=>({consents:[c,...s.consents],accounts:s.accounts.map(a=>a.id===accountId?{...a,consentId:c.id,source:'SANDBOX_AA',syncStatus:'CONNECTED',lastSyncedAt:new Date().toISOString()}:a)}));return c;},
  disconnect:id=>set(s=>({accounts:s.accounts.map(a=>a.id===id?{...a,syncStatus:'DISCONNECTED',consentId:undefined}:a),consents:s.consents.map(c=>c.accountIds.includes(id)?{...c,status:'REVOKED',revokedAt:new Date().toISOString()}:c)})),
  removeAccount:id=>set(s=>({accounts:s.accounts.filter(a=>a.id!==id),transactions:s.transactions.filter(t=>t.accountId!==id),raw:s.raw.filter(t=>t.accountId!==id)}))
}),{name:'finova-bank-v1',storage:createJSONStorage(()=>localStorage,{replacer:(_k,v)=>typeof v==='bigint'?{__bigint__:v.toString()}:v,reviver:(_k,v)=>v&&typeof v==='object'&&'__bigint__' in v?BigInt((v as {__bigint__:string}).__bigint__):v}),partialize:s=>({accounts:s.accounts,consents:s.consents,raw:s.raw,transactions:s.transactions,rules:s.rules,scanCredits:s.scanCredits,premium:s.premium})}));
