'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Line, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { AlertTriangle, ArrowDownRight, ArrowUpRight, Download, Info, Printer, RefreshCw, ShieldCheck, Sparkles, WalletCards } from 'lucide-react';
import { useFinova } from '@/lib/data/store';
import { buildForecast, forecastToJSON, type ForecastHorizon, type ForecastScenario, type Forecast } from '@/lib/forecast/engine';
import { forecastUsesLiveClientData, workspaceFromStore } from '@/lib/forecast/source';

type F = ReturnType<typeof forecastToJSON> & { gstLiabilityPaise:string };
const n=(p:string)=>Number(p)/100; const money=(p:string)=>`₹${n(p).toLocaleString('en-IN',{maximumFractionDigits:0})}`; const shortDate=(s:string)=>new Date(`${s}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short'}); const csvEscape=(x:string)=>`"${x.replaceAll('"','""')}"`;

export function ForecastDashboard() {
  const workspace = useFinova(); const [horizon,setHorizon]=useState<ForecastHorizon>(30); const [scenario,setScenario]=useState<ForecastScenario>('expected'); const [safetyBuffer,setSafetyBuffer]=useState(20000); const [f,setF]=useState<F|null>(null); const [premium,setPremium]=useState(process.env.NEXT_PUBLIC_FINOVA_PREMIUM==='true'); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [retry,setRetry]=useState(0);
  const fetchServer=useCallback(async()=>{try{const q=new URLSearchParams({horizon:String(horizon),scenario,safetyBuffer:String(safetyBuffer)});const r=await fetch(`/api/forecast?${q}`,{cache:'no-store'});const j=await r.json().catch(()=>null) as {success?:boolean;data?:{forecast:F;premium?:boolean};error?:string}|null;if(!r.ok||!j?.data?.forecast)throw new Error(j?.error||'Forecast could not be loaded. Check your account access and retry.');setF(j.data.forecast);setPremium(Boolean(j.data.premium));}catch(e){setError(e instanceof Error?e.message:'Forecast could not be loaded.');}finally{setLoading(false);}},[horizon,scenario,safetyBuffer]);
  const build=useCallback(()=>{setLoading(true);setError('');try{if(forecastUsesLiveClientData()){const value=buildForecast({...workspaceFromStore(workspace),now:new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'}),horizon,scenario,safetyBufferPaise:BigInt(Math.round(safetyBuffer*100))});setF(forecastToJSON(value) as F);setPremium(process.env.NEXT_PUBLIC_FINOVA_PREMIUM==='true');}else{void fetchServer();}}catch(e){setError(e instanceof Error?e.message:'Forecast could not be built from the current workspace.');}finally{if(forecastUsesLiveClientData())setLoading(false);}},[horizon,scenario,safetyBuffer,workspace,fetchServer]);
  useEffect(()=>{void build();},[build,retry]);
  useEffect(()=>{if(f&&!premium&&horizon!==30)setHorizon(30);},[f,premium,horizon]);
  const chart=useMemo(()=>f?.points.map((p)=>({date:shortDate(p.date),balance:n(p.balancePaise),best:n(p.bestPaise),worst:n(p.worstPaise),in:n(p.inflowPaise),out:n(p.outflowPaise)}))??[],[f]);
  const incoming=f?money(f.expectedIncomingPaise):'—', expenses=f?money(f.expectedExpensesPaise):'—', projected=f?money(f.projectedPositionPaise):'—', cash=f?money(f.currentCashPaise):'—';
  function exportCsv(){if(!f)return;const rows=[['Date','Balance','Best','Worst','Cash In','Cash Out'],...f.points.map(p=>[p.date,money(p.balancePaise),money(p.bestPaise),money(p.worstPaise),money(p.inflowPaise),money(p.outflowPaise)])];const blob=new Blob([rows.map(r=>r.map(String).map(csvEscape).join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`finova-cash-forecast-${f.horizon}d.csv`;a.click();URL.revokeObjectURL(a.href);}
  if(loading)return <div className="forecast-loading" role="status"><RefreshCw className="spin" size={20}/> Building your cash forecast…</div>;
  if(error)return <div className="forecast-error" role="alert"><AlertTriangle size={20}/><div><strong>Forecast unavailable</strong><p>{error}</p><button type="button" onClick={()=>setRetry((x)=>x+1)}>Retry</button></div></div>;
  if(!f)return <div className="forecast-empty"><Info size={20}/><h2>No forecast data yet</h2><p>Add at least one cash account, invoice or expense to build a projection.</p></div>;
  const warning=f.firstBelowBuffer||f.firstBelowZero; const topIn=[...f.events].filter(e=>e.direction==='in').sort((a,b)=>Number(b.amountPaise)-Number(a.amountPaise)).slice(0,3); const topOut=[...f.events].filter(e=>e.direction==='out').sort((a,b)=>Number(b.amountPaise)-Number(a.amountPaise)).slice(0,3);
  const checkpoints=[30,60,90,180,365].filter((d)=>d<=f.horizon).map((d)=>({d,balance:n(f.points[Math.min(d,f.points.length-1)]!.balancePaise)}));
  return <div className="forecast-page"><div className="forecast-hero"><div><div className="forecast-eyebrow"><WalletCards size={15}/> Cash-flow forecast {forecastUsesLiveClientData()&&<span className="demo-badge">Using demo data</span>}</div><h1>Where is your cash heading?</h1><p>Projected movement based on recorded invoices, expenses, cash accounts and detected recurring patterns. Forecasts are estimates, not financial advice.</p></div><div className="forecast-actions"><button onClick={exportCsv}><Download size={16}/> Export CSV</button><button onClick={()=>window.print()}><Printer size={16}/> Print / PDF</button></div></div>
    {f.limitedData&&<div className="forecast-notice"><Info size={18}/><span><strong>Limited history:</strong> less than three months of records are available, so invoice and recurring-item assumptions have greater weight.</span></div>}
    <div className="forecast-controls"><div><span>Horizon</span>{([30,60,90,180,365] as ForecastHorizon[]).map((x)=><button disabled={!premium&&x!==30} className={horizon===x?'active':''} key={x} onClick={()=>setHorizon(x)}>{x===365?'12 mo':`${x}d`}</button>)}</div><div><span>Scenario</span>{(['expected','best','worst'] as ForecastScenario[]).map((x)=><button disabled={!premium} className={scenario===x?'active':''} key={x} onClick={()=>setScenario(x)}>{x[0]!.toUpperCase()+x.slice(1)}</button>)}</div><label><span>Safety buffer</span><input type="number" min="0" value={safetyBuffer} onChange={(e)=>setSafetyBuffer(Number(e.target.value)||0)}/></label></div>
    <div className="forecast-cards"><div className="forecast-card"><span>Opening cash</span><strong>{cash}</strong><small>Bank and cash accounts currently available.</small></div><div className="forecast-card"><span>Expected incoming</span><strong className="positive">+ {incoming}</strong><small>Open invoices weighted by recorded payment behaviour.</small></div><div className="forecast-card"><span>Expected outgoing</span><strong className="negative">− {expenses}</strong><small>Recurring patterns, historical spend and estimated tax liability.</small></div><div className="forecast-card"><span>Projected balance</span><strong>{projected}</strong><small>Opening cash + projected incoming − projected outgoing.</small></div></div>
    <div className="forecast-mini-grid"><div><span>GST liability estimate</span><strong>{money(f.gstLiabilityPaise)}</strong></div><div><span>Runway</span><strong>{f.runwayMonths===null?'Not available':`${f.runwayMonths.toFixed(1)} months`}</strong></div><div><span>30-day position</span><strong>{checkpoints.find(x=>x.d===30)?money(String(Math.round((checkpoints.find(x=>x.d===30)!.balance)*100))):'—'}</strong></div><div><span>Safety-buffer alert</span><strong>{warning?`Around ${shortDate(warning)}`:'No breach projected'}</strong></div></div>
    {!premium&&<div className="forecast-notice"><Sparkles size={18}/><span><strong>Premium preview:</strong> this build keeps the full calculation visible in a 30-day window. Extended horizons and scenario controls unlock when premium is enabled.</span></div>}
    <div className="forecast-confidence"><ShieldCheck size={18}/><strong>Confidence: {f.confidence}</strong><span>{f.confidenceReasons.join(' ')}</span></div>
    <section className="forecast-panel"><div className="forecast-panel-head"><div><h2>Projected cash balance</h2><p>Expected path with best/worst invoice-timing band and safety-buffer reference.</p></div>{warning&&<span className="forecast-warning"><AlertTriangle size={15}/> Below buffer around {shortDate(warning)}</span>}</div><div className="forecast-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{top:10,right:15,left:0,bottom:5}}><defs><linearGradient id="bestBand" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#10b981" stopOpacity=".20"/><stop offset="100%" stopColor="#10b981" stopOpacity=".03"/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} opacity=".15"/><XAxis dataKey="date" minTickGap={24}/><YAxis tickFormatter={(v)=>`₹${Math.round(v/1000)}k`}/><Tooltip formatter={(v)=>`₹${Number(v).toLocaleString('en-IN')}`}/><Area type="monotone" dataKey="best" stroke="none" fill="url(#bestBand)"/><Line type="monotone" dataKey="balance" stroke="#10b981" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="worst" stroke="#ef4444" strokeDasharray="5 5" dot={false}/><ReferenceLine y={0} stroke="#ef4444" strokeDasharray="4 4"/><ReferenceLine y={safetyBuffer} stroke="#f59e0b" strokeDasharray="4 4"/></AreaChart></ResponsiveContainer></div></section>
    <div className="forecast-two"><section className="forecast-panel"><div className="forecast-panel-head"><div><h2>Cash in vs cash out</h2><p>Weekly projected movement.</p></div></div><div className="forecast-chart small"><ResponsiveContainer width="100%" height="100%"><BarChart data={f.weeklyCashIn.map((x,i)=>({label:shortDate(x.label),in:n(x.amountPaise),out:n(f.weeklyCashOut[i]?.amountPaise??'0')}))}><CartesianGrid strokeDasharray="3 3" vertical={false} opacity=".15"/><XAxis dataKey="label"/><YAxis tickFormatter={(v)=>`₹${Math.round(v/1000)}k`}/><Tooltip/><Bar dataKey="in" fill="#10b981" radius={[6,6,0,0]}/><Bar dataKey="out" fill="#ef4444" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></section><section className="forecast-panel"><div className="forecast-panel-head"><div><h2>Key drivers</h2><p>Largest scheduled movements inside the horizon.</p></div></div><div className="forecast-drivers"><div><h3><ArrowUpRight size={15}/> Inflows</h3>{topIn.length?topIn.map(e=><p key={e.id}><span>{e.label}</span><strong>+{money(e.amountPaise)}</strong></p>):<p>No projected inflows.</p>}</div><div><h3><ArrowDownRight size={15}/> Outflows</h3>{topOut.length?topOut.map(e=><p key={e.id}><span>{e.label}</span><strong>−{money(e.amountPaise)}</strong></p>):<p>No projected outflows.</p>}</div></div></section></div>
    <section className="forecast-panel"><div className="forecast-panel-head"><div><h2>Projection checkpoints</h2><p>Reference points across the selected horizon.</p></div></div><div className="forecast-checkpoints">{checkpoints.map(x=><div key={x.d}><span>{x.d===365?'12 months':`${x.d} days`}</span><strong>{money(String(Math.round(x.balance*100)))}</strong></div>)}</div></section>
  </div>;
}
