import type { BankAccount, BankTransaction } from '@/lib/bank/types';
import { PdfDoc, downloadPdf, hex, type Rgb } from './pdf';

const INK = hex('#14213d'), MUTED = hex('#6b7893'), RULE = hex('#d9dfeb'), ACCENT = hex('#2f4b9a'), SOFT = hex('#f3f5fa'), GREEN = hex('#15803d'), RED = hex('#b91c1c'), WHITE: [number, number, number] = [1, 1, 1];
const inr = (p: bigint) => (Number(p) / 100).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const fmt = (iso: string) => new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${iso.slice(0, 10)}T00:00:00`));

/** Statements can look back at most this many days from today. */
export const STATEMENT_MAX_DAYS = 30;
export const isoDaysAgo = (n: number) => { const d = new Date(); d.setDate(d.getDate() - n); return d.toLocaleDateString('en-CA'); };

export function buildStatementPdf(opts: { transactions: BankTransaction[]; accounts: BankAccount[]; accountId: string; from: string; to: string }): Uint8Array {
  const { accounts, accountId, from, to } = opts;
  const txs = opts.transactions
    .filter((t) => (!accountId || t.accountId === accountId) && t.date.slice(0, 10) >= from && t.date.slice(0, 10) <= to)
    .sort((a, b) => a.date.localeCompare(b.date));
  const acct = accounts.find((a) => a.id === accountId);
  const credits = txs.filter((t) => t.direction === 'CREDIT').reduce((s, t) => s + t.amountPaise, 0n);
  const debits = txs.filter((t) => t.direction === 'DEBIT').reduce((s, t) => s + t.amountPaise, 0n);

  const d = new PdfDoc(); const L = 40, R = d.width - 40, W = R - L;
  const cDate = L + 8, cDesc = L + 84, cDeb = L + W * 0.76, cCred = R - 8;
  const header = () => {
    d.rect(0, 0, d.width, 8, ACCENT);
    d.text('Finova', L, 58, { font: 'serifBold', size: 24, color: INK });
    d.text('Account statement', L, 74, { font: 'serifItalic', size: 10.5, color: MUTED });
    d.text('STATEMENT', R, 56, { font: 'serif', size: 22, color: ACCENT, align: 'right', spacing: 3 });
    d.text(`${fmt(from)} - ${fmt(to)}`, R, 74, { font: 'sansBold', size: 10, color: INK, align: 'right' });
  };
  const tableHead = (y: number) => {
    d.rect(L, y, W, 24, INK); const ty = y + 16;
    d.text('DATE', cDate, ty, { font: 'sansBold', size: 8, color: WHITE, spacing: 1 });
    d.text('DESCRIPTION', cDesc, ty, { font: 'sansBold', size: 8, color: WHITE, spacing: 1 });
    d.text('DEBIT (Rs.)', cDeb, ty, { font: 'sansBold', size: 8, color: WHITE, align: 'right', spacing: 1 });
    d.text('CREDIT (Rs.)', cCred, ty, { font: 'sansBold', size: 8, color: WHITE, align: 'right', spacing: 1 });
    return y + 24;
  };
  const footer = () => {
    d.line(L, 802, R, 802, RULE);
    d.text('Generated by Finova from imported bank transactions. Not a bank-issued statement.', L, 817, { font: 'serifItalic', size: 9, color: MUTED });
    d.text(`Page ${d.pageCount}`, R, 817, { font: 'sans', size: 8.5, color: MUTED, align: 'right' });
  };

  header();
  let y = 112;
  d.text('ACCOUNT', L, y, { font: 'sansBold', size: 8, color: MUTED, spacing: 1 });
  d.text(acct ? `${acct.bankName}  ${acct.maskedAccountNumber}` : 'All accounts', L, y + 20, { font: 'serifBold', size: 15, color: INK });
  if (acct) d.text(`${acct.accountType.replace('_', ' ')}`, L, y + 36, { font: 'sans', size: 9, color: MUTED });
  d.text('Generated on', R, y, { font: 'sans', size: 8.5, color: MUTED, align: 'right' });
  d.text(fmt(new Date().toLocaleDateString('en-CA')), R, y + 16, { font: 'sansBold', size: 10, color: INK, align: 'right' });
  y += 56;

  // Summary cards
  const cw = (W - 24) / 4;
  const cards: [string, string, Rgb][] = [['Transactions', String(txs.length), INK], ['Total credits', inr(credits), GREEN], ['Total debits', inr(debits), RED], ['Net movement', `${credits - debits < 0n ? '-' : ''}${inr(credits - debits < 0n ? debits - credits : credits - debits)}`, INK]];
  cards.forEach(([k, v, c], i) => {
    const x = L + i * (cw + 8);
    d.rect(x, y, cw, 50, SOFT, RULE);
    d.text(k.toUpperCase(), x + 10, y + 17, { font: 'sansBold', size: 7.5, color: MUTED, spacing: 0.8 });
    d.text(v, x + 10, y + 38, { font: 'serifBold', size: 14, color: c });
  });
  y += 70;

  y = tableHead(y);
  if (!txs.length) d.text('No transactions in the selected period.', L + W / 2, y + 40, { font: 'serifItalic', size: 12, color: MUTED, align: 'center' });
  txs.forEach((t, i) => {
    const desc = d.wrap(`${t.merchant}${t.narration && t.narration !== t.merchant ? ' - ' + t.narration : ''}`, 'serif', 10.5, cDeb - cDesc - 60).slice(0, 2);
    const h = desc.length > 1 ? 34 : 24;
    if (y + h > 790) { footer(); d.addPage(); header(); y = tableHead(100); }
    if (i % 2 === 1) d.rect(L, y, W, h, SOFT);
    d.text(fmt(t.date), cDate, y + 16, { font: 'sans', size: 9, color: INK });
    desc.forEach((l, k) => d.text(l, cDesc, y + 16 + k * 12, { font: 'serif', size: 10.5, color: INK }));
    const amt = inr(t.amountPaise);
    if (t.direction === 'DEBIT') d.text(amt, cDeb, y + 16, { font: 'sansBold', size: 9.5, color: RED, align: 'right' });
    else d.text(amt, cCred, y + 16, { font: 'sansBold', size: 9.5, color: GREEN, align: 'right' });
    y += h;
  });
  d.line(L, y, R, y, INK, 0.9);
  if (txs.length) {
    if (y + 30 > 790) { footer(); d.addPage(); header(); y = 100; }
    d.text('TOTAL', cDesc, y + 20, { font: 'sansBold', size: 9, color: INK, spacing: 1 });
    d.text(inr(debits), cDeb, y + 20, { font: 'sansBold', size: 10, color: RED, align: 'right' });
    d.text(inr(credits), cCred, y + 20, { font: 'sansBold', size: 10, color: GREEN, align: 'right' });
  }
  footer();
  return d.build({ title: `Statement ${from} to ${to}` });
}

export function downloadStatementPdf(opts: Parameters<typeof buildStatementPdf>[0]) {
  downloadPdf(buildStatementPdf(opts), `finova-statement_${opts.from}_to_${opts.to}.pdf`);
}
