'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowDownRight, BarChart3, BookOpen, CircleHelp, Home, LayoutDashboard, Receipt, Search, Settings, Sparkles, WalletCards, X } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { useFinova } from '@/lib/data/store';
import { todayISO } from '@/lib/data/format';
import { executeSpec } from '@/lib/nlq/executor';
import { parseQuestion } from '@/lib/nlq/parser';
import { shouldRunNlq } from '@/lib/nlq/router';
import { querySpecSchema, type NlqGroup, type QuerySpec } from '@/lib/nlq/types';
import { relaxationSuggestions } from '@/lib/nlq/relax';
import { isFollowUp, mergeFollowUp } from '@/lib/nlq/context';
import { NlResults } from './global-search/nl-results';
import { NlSuggestions } from './global-search/nl-suggestions';

export type SearchAction = 'route' | 'settings' | 'help';
type SearchItem = { id:string;label:string;description:string;keywords:string;href?:string;action?:SearchAction;icon:typeof Search };
const SEARCH_ITEMS:SearchItem[]=[
{id:'dashboard',label:'Dashboard',description:'Financial overview and key metrics',keywords:'home overview metrics',href:'/dashboard',icon:LayoutDashboard},{id:'transactions',label:'Transactions',description:'Journal entries and transaction history',keywords:'journal entries ledger',href:'/journal',icon:WalletCards},{id:'invoices',label:'Invoices',description:'Customer invoices and money owed to you',keywords:'billing payments receivables',href:'/invoices',icon:Receipt},{id:'expenses',label:'Expenses',description:'Track and review business spending',keywords:'spending costs payments',href:'/expenses',icon:ArrowDownRight},{id:'reports',label:'Reports',description:'Financial reports and statements',keywords:'profit loss balance sheet statements',href:'/reports',icon:BarChart3},{id:'chart of accounts',label:'Chart of Accounts',description:'Review your account structure',keywords:'accounts coa ledger',href:'/accounts',icon:BookOpen},{id:'settings',label:'Settings',description:'Account, appearance, notifications and security',keywords:'preferences theme account security',action:'settings',icon:Settings},{id:'help support',label:'Help & Support',description:'FAQs, troubleshooting and support',keywords:'help faq support troubleshooting',action:'help',icon:CircleHelp},{id:'home',label:'Home',description:'Return to the Finova home page',keywords:'landing start',href:'/',icon:Home},
];
function toQuery(spec:QuerySpec){const f=spec.filters;const p=new URLSearchParams();if(f.category?.[0])p.set('category',f.category[0]);if(f.vendor?.[0])p.set('vendor',f.vendor[0]);if(f.customer?.[0])p.set('customer',f.customer[0]);if(f.status?.length)p.set('status',f.status.join(','));if(f.paymentMethod?.[0])p.set('method',f.paymentMethod[0]);if(f.source?.[0])p.set('source',f.source[0]);if(f.account?.[0])p.set('account',f.account[0]);if(f.dateRange){p.set(f.dateRange.field==='dueDate'?'dueFrom':'from',f.dateRange.from);p.set(f.dateRange.field==='dueDate'?'dueTo':'to',f.dateRange.to);}if(f.amount?.min!==undefined)p.set('min',String(f.amount.min));if(f.amount?.max!==undefined)p.set('max',String(f.amount.max));if(f.text)p.set('q',f.text);if(spec.sort)p.set('sort',`${spec.sort.field}:${spec.sort.dir}`);return p.toString();}
function destination(entity:string,spec:QuerySpec){const path=entity==='expense'?'/expenses':entity==='invoice'?'/invoices':entity==='transaction'?'/journal':entity==='account'?'/accounts':'/invoices';const q=toQuery(spec);return `${path}${q?`?${q}`:''}`;}

export function GlobalSearch({onOpenSettings,onOpenHelp}:{onOpenSettings:()=>void;onOpenHelp:()=>void}){
 const router=useRouter();const ws=useFinova();const [query,setQuery]=useState('');const [open,setOpen]=useState(false);const [highlighted,setHighlighted]=useState(0);const [nlSpec,setNlSpec]=useState<QuerySpec|null>(null);const [nlGroups,setNlGroups]=useState<NlqGroup[]|null>(null);const [nlUnresolved,setNlUnresolved]=useState<string[]>([]);const [nlAlternatives,setNlAlternatives]=useState<string[]>([]);const rootRef=useRef<HTMLDivElement>(null);const inputRef=useRef<HTMLInputElement>(null);
 const results=useMemo(()=>{const n=query.trim().toLowerCase();if(!n)return SEARCH_ITEMS.slice(0,6);return SEARCH_ITEMS.filter(i=>`${i.label} ${i.description} ${i.keywords}`.toLowerCase().includes(n));},[query]);
 const examples=useMemo(()=>{const cats=[...new Set(ws.expenses.map(e=>e.category))];const customer=ws.invoices[0]?.customer;return [`Show me expenses this month`,cats[0]?`Show me everything I spent on ${cats[0]}`:'Show me my expenses this month',customer?`Show me ${customer} invoices`:'Show me unpaid invoices','What did I pay last month?','Show invoices over ₹20k'];},[ws.expenses,ws.invoices]);
 const runNl=async(text:string)=>{
   const question=text.replace(/^\?/,'').trim();
   const stored=typeof window!=='undefined'?window.localStorage.getItem('finova:nlq-context'):null;
   const context=stored?(()=>{try{const parsed=JSON.parse(stored) as {spec:QuerySpec;at:number};return Date.now()-parsed.at<=300000?parsed.spec:undefined;}catch{return undefined;}})():undefined;
   if(process.env.NEXT_PUBLIC_DATA_SOURCE==='prisma'){try{const res=await fetch('/api/search/nl',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question,context})});const json=await res.json() as {success?:boolean;data?:{spec:QuerySpec;groups:NlqGroup[];unresolved:string[];alternatives:string[]};error?:string};if(json.success&&json.data?.spec){setNlSpec(json.data.spec);setNlGroups(json.data.groups??[]);setNlUnresolved(json.data.unresolved??[]);setNlAlternatives(json.data.alternatives??[]);setQuery(text);setOpen(true);try{window.localStorage.setItem('finova:nlq-context',JSON.stringify({spec:json.data.spec,at:Date.now()}));}catch{}return;}}catch{/* deterministic local fallback */}}
   const nowIso=todayISO();const followed=context&&isFollowUp(question,nowIso)?mergeFollowUp(context,question,nowIso):undefined;const result=followed?{spec:{...followed,confidence:Math.max(followed.confidence,0.75)},unresolved:[] as string[],alternatives:[] as string[]}:parseQuestion(question,{accounts:ws.accounts,entries:ws.entries,invoices:ws.invoices,expenses:ws.expenses},nowIso);if(result.spec){setNlSpec(result.spec);const localWs={accounts:ws.accounts,entries:ws.entries,invoices:ws.invoices,expenses:ws.expenses};setNlGroups(executeSpec(localWs,result.spec,todayISO()));setNlUnresolved(result.unresolved);setNlAlternatives(result.alternatives);setQuery(text);setOpen(true);try{window.localStorage.setItem('finova:nlq-context',JSON.stringify({spec:result.spec,at:Date.now()}));}catch{}}else{setNlSpec(null);setNlGroups(null);}
 };
 useEffect(()=>{setHighlighted(0);if(!shouldRunNlq(query))setNlSpec(null);},[query]);
 useEffect(()=>{const onVoiceSearch=(e:Event)=>{const detail=(e as CustomEvent<string>).detail;setQuery(typeof detail==='string'?detail:'');setOpen(true);inputRef.current?.focus();};window.addEventListener('finova:global-search',onVoiceSearch);return()=>window.removeEventListener('finova:global-search',onVoiceSearch);},[]);
 useEffect(()=>{const pointer=(e:MouseEvent)=>{if(rootRef.current&&!rootRef.current.contains(e.target as Node)){setOpen(false);try{window.localStorage.removeItem('finova:nlq-context')}catch{}}};const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();inputRef.current?.focus();setOpen(true);}};document.addEventListener('mousedown',pointer);document.addEventListener('keydown',key);return()=>{document.removeEventListener('mousedown',pointer);document.removeEventListener('keydown',key)}},[]);
 const select=(item:SearchItem)=>{setOpen(false);setQuery('');setNlSpec(null);setNlGroups(null);try{window.localStorage.removeItem('finova:nlq-context')}catch{};if(item.action==='settings')return onOpenSettings();if(item.action==='help')return onOpenHelp();if(item.href)router.push(item.href);};
 const key=(e:React.KeyboardEvent<HTMLInputElement>)=>{if(e.key==='Escape'){e.preventDefault();setOpen(false);try{window.localStorage.removeItem('finova:nlq-context')}catch{};inputRef.current?.blur();}else if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);setHighlighted(i=>results.length?(i+1)%results.length:0)}else if(e.key==='ArrowUp'){e.preventDefault();setOpen(true);setHighlighted(i=>results.length?(i-1+results.length)%results.length:0)}else if(e.key==='Enter'){e.preventDefault();if(shouldRunNlq(query)){runNl(query);return;}if(open&&results[highlighted])select(results[highlighted]);}};
 const applySpec=(s:QuerySpec)=>{const next=querySpecSchema.parse(s);setNlSpec(next);setNlGroups(executeSpec({accounts:ws.accounts,entries:ws.entries,invoices:ws.invoices,expenses:ws.expenses},next,todayISO()));setNlUnresolved(next.unresolved);setNlAlternatives([]);try{window.localStorage.setItem('finova:nlq-context',JSON.stringify({spec:next,at:Date.now()}));}catch{}};
 const openAll=(s:QuerySpec,entity:string)=>{setOpen(false);setNlSpec(null);setNlGroups(null);setNlUnresolved([]);setNlAlternatives([]);setQuery('');router.push(destination(entity,s));};
 return <div ref={rootRef} className="global-search"><div className="search-box" role="search"><Search size={19} aria-hidden="true"/><input ref={inputRef} role="combobox" aria-label="Global search and financial questions" aria-expanded={open} aria-controls="global-search-results" aria-autocomplete="list" autoComplete="off" value={query} onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setOpen(true)}} onKeyDown={key} placeholder="Search or ask: “what did I spend last month?” · Ctrl/⌘ K · AI Ctrl/⌘ J"/>{query?<button type="button" className="search-clear" aria-label="Clear search" onClick={()=>{setQuery('');setNlSpec(null);setNlGroups(null);try{window.localStorage.removeItem('finova:nlq-context')}catch{};inputRef.current?.focus()}}><X size={14}/></button>:<kbd>⌘ K</kbd>}</div>
 {open&&<div id="global-search-results" className="search-results" role="listbox" aria-label="Global search results">{shouldRunNlq(query)&&!nlSpec&&<button className="search-ask-row" onClick={()=>runNl(query)}><Sparkles size={16}/><span>Ask: <strong>{query}</strong></span><small>Enter</small></button>}{nlSpec?<><NlResults spec={nlSpec} groups={nlGroups??[]} unresolved={nlUnresolved} alternatives={nlAlternatives} relaxations={relaxationSuggestions({accounts:ws.accounts,entries:ws.entries,invoices:ws.invoices,expenses:ws.expenses},nlSpec,todayISO())} onSpec={applySpec} onOpen={openAll} onAsk={()=>window.dispatchEvent(new CustomEvent('finova:assistant-question',{detail:query}))}/><NlSuggestions examples={examples} onPick={runNl}/></>:<>{query.trim()===''?<NlSuggestions examples={examples} onPick={runNl}/>:null}<div className="search-results-head"><span>{query.trim()?'Search results':'Quick navigation'}</span><span>{results.length} {results.length===1?'result':'results'}</span></div>{results.length?results.map((item,index)=>{const Icon=item.icon;return <button type="button" role="option" id={`search-option-${item.id.replace(/\s+/g,'-')}`} tabIndex={-1} aria-selected={index===highlighted} key={item.id} className={`search-result ${index===highlighted?'selected':''}`} onMouseEnter={()=>setHighlighted(index)} onClick={()=>select(item)}><span className="search-result-icon"><Icon size={16}/></span><span className="search-result-copy"><strong>{item.label}</strong><small>{item.description}</small></span><span className="search-result-hint">Open</span></button>}) : <div className="search-no-results"><Search size={22}/><strong>No results found</strong><span>Try a dashboard module or ask a financial question.</span></div>}</>}</div>}</div>;
}
