'use client';

import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, Eye, EyeOff, Loader2, Mail, ShieldCheck, X } from 'lucide-react';
import { authAdapter, normalizeEmail, passwordStrength, registrationSchema, signInSchema } from '@/lib/demo-auth';
import './login-modal.css';

type Mode = 'signin' | 'signup'; type Step = 'chooser' | 'email' | 'password' | 'success' | 'register';
export function LoginModal({ onClose, initialMode = 'signin' }: { onClose: () => void; initialMode?: Mode }) {
  const [mode, setMode] = useState<Mode>(initialMode); const [step, setStep] = useState<Step>('chooser');
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [terms, setTerms] = useState(false); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(false);
  const dialogRef = useRef<HTMLElement>(null); const triggerRestore = useRef<Element | null>(null); const alive = useRef(true);
  useEffect(() => () => { alive.current = false; }, []);
  useEffect(() => { triggerRestore.current = document.activeElement; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = ''; if (triggerRestore.current instanceof HTMLElement) triggerRestore.current.focus(); }; }, []);
  useEffect(() => { const t = window.setTimeout(() => dialogRef.current?.querySelector<HTMLElement>('[data-autofocus="true"], input, button:not([aria-label="Close login"])')?.focus(), 60); return () => clearTimeout(t); }, [step]);
  const close = useCallback(() => { if (!loading) onClose(); }, [loading, onClose]);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); close(); return; } if (event.key !== 'Tab' || !dialogRef.current) return; const items = [...dialogRef.current.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), select:not(:disabled)')]; if (!items.length) return; const first = items[0]!; const last = items[items.length - 1]!; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; document.addEventListener('keydown', onKey); return () => document.removeEventListener('keydown', onKey); }, [close]);
  const reset = () => { setError(''); setNotice(''); };
  const choose = (next: Mode) => { reset(); setMode(next); setStep(next === 'signin' ? 'email' : 'register'); };
  const run = async (task: () => Promise<{ ok: boolean; message: string; code?: string }>) => { reset(); setLoading(true); try { const result = await task(); if (!alive.current) return; if (result.ok) { setNotice(result.message); setStep('success'); } else { setError(result.message); if (result.code === 'DUPLICATE') { setMode('signup'); setStep('register'); } }  } catch { if (alive.current) setError('We could not complete that request. Please try again.'); } finally { if (alive.current) setLoading(false); } };
  const submitEmail = (e: FormEvent) => { e.preventDefault(); const p = authAdapter.validateEmail(email); if (p) return setError(p); setEmail(normalizeEmail(email)); setError(''); setStep('password'); };
  const submitPassword = (e: FormEvent) => { e.preventDefault(); const parsed = signInSchema.safeParse({ email, password }); if (!parsed.success) return setError('Enter a valid email and password.'); void run(() => authAdapter.loginWithEmail(normalizeEmail(email), password)).then(() => undefined); };
  const submitRegister = (e: FormEvent) => { e.preventDefault(); const parsed = registrationSchema.safeParse({ name, email, password, confirmPassword: confirm, terms }); if (!parsed.success) return setError(parsed.error.issues[0]?.message ?? 'Check the form and try again.'); const p = authAdapter.validateName(name) ?? authAdapter.validateEmail(email) ?? authAdapter.validatePassword(password); if (p) return setError(p); void run(() => authAdapter.register(name, email, password)).then(() => undefined); };
  const strength = passwordStrength(password);
  const feedback = <>{error && <p className="finova-login-error" role="alert">{error} {error.includes('No account') && <button type="button" className="finova-login-link" onClick={() => choose('signup')}>Create an account</button>}{error.includes('already registered') && <button type="button" className="finova-login-link" onClick={() => choose('signin')}>Sign in instead</button>}</p>}{notice && <p className="finova-login-notice" role="status">{notice}</p>}</>;
  return <div className="finova-login-backdrop" role="presentation" onMouseDown={(e) => { if (e.currentTarget === e.target) close(); }}><section ref={dialogRef} className="finova-login-modal" role="dialog" aria-modal="true" aria-labelledby="finova-login-title">
    <button className="finova-login-close" type="button" aria-label="Close login" onClick={close} disabled={loading}><X size={19}/></button>
    <div className="finova-login-brand"><ShieldCheck size={18}/><span>FINOVA SECURE ACCESS</span></div>
    <div className="finova-login-heading"><h2 id="finova-login-title">{step === 'success' ? 'Welcome to Finova' : mode === 'signup' ? 'Create your Finova account' : 'Welcome back'}</h2><p>{step === 'success' ? 'Your demo account is ready to use.' : mode === 'signup' ? 'Set up your workspace identity in a few steps.' : 'Sign in to continue to your Finova workspace.'}</p></div>
    <div className="finova-auth-switch" role="tablist" aria-label="Authentication mode"><button type="button" role="tab" aria-selected={mode === 'signin'} className={mode === 'signin' ? 'active' : ''} onClick={() => choose('signin')}>Sign in</button><button type="button" role="tab" aria-selected={mode === 'signup'} className={mode === 'signup' ? 'active' : ''} onClick={() => choose('signup')}>Create new account</button></div>
    {step === 'chooser' && <div className="finova-mode-cards"><button type="button" className="finova-mode-card" onClick={() => choose('signin')}><strong>Sign in</strong><span>Use an existing Finova account.</span></button><button type="button" className="finova-mode-card" onClick={() => choose('signup')}><strong>Create new account</strong><span>Register a new account with email and password.</span></button></div>}
    {step === 'email' && <form className="finova-login-step" onSubmit={submitEmail} noValidate><label>Email<input data-autofocus="true" type="email" name="email" autoComplete="email" placeholder="you@gmail.com" value={email} aria-invalid={!!error} onChange={(e) => { setEmail(e.target.value); setError(''); }}/></label>{feedback}<button type="submit" className="finova-login-primary">Continue <ArrowRight size={17}/></button></form>}
    {step === 'password' && <form className="finova-login-step" onSubmit={submitPassword} noValidate><button type="button" className="finova-login-back" onClick={() => { setPassword(''); setStep('email'); }} disabled={loading}><ArrowLeft size={16}/> Back</button><p className="finova-login-identity"><Mail size={15}/> {email}</p><label>Password<div className="password-field"><input data-autofocus="true" type={showPassword ? 'text' : 'password'} name="password" autoComplete="current-password" placeholder="Enter your password" value={password} aria-invalid={!!error} onChange={(e) => { setPassword(e.target.value); setError(''); }}/><button type="button" aria-label={showPassword ? 'Hide password' : 'Show password'} onClick={() => setShowPassword((x) => !x)}>{showPassword ? <EyeOff size={16}/> : <Eye size={16}/>}</button></div></label><div className="finova-login-row"><button type="button" className="finova-login-link" onClick={() => setNotice('Password recovery will connect to the QuikIT auth flow when enabled. No message was sent.')}>Forgot password?</button></div>{feedback}<button type="submit" className="finova-login-primary" disabled={loading}>{loading ? <><Loader2 size={17} className="finova-spin"/> Signing in…</> : <>Sign in <ArrowRight size={17}/></>}</button></form>}
    {step === 'register' && <form className="finova-login-step" onSubmit={submitRegister} noValidate><label>Full name<input data-autofocus="true" type="text" name="name" autoComplete="name" placeholder="Your name" value={name} aria-invalid={!!error} onChange={(e) => { setName(e.target.value); setError(''); }}/></label><label>Email<input type="email" name="email" autoComplete="email" placeholder="you@gmail.com" value={email} aria-invalid={!!error} onChange={(e) => { setEmail(e.target.value); setError(''); }}/></label><label>Password<div className="password-field"><input type={showPassword ? 'text' : 'password'} name="new-password" autoComplete="new-password" placeholder="At least 6 characters" value={password} aria-invalid={!!error} onChange={(e) => { setPassword(e.target.value); setError(''); }}/><button type="button" aria-label={showPassword ? 'Hide password' : 'Show password'} onClick={() => setShowPassword((x) => !x)}>{showPassword ? <EyeOff size={16}/> : <Eye size={16}/>}</button></div></label><div className={`password-strength strength-${strength.score}`}><span><i style={{width:`${Math.max(20,strength.score/5*100)}%`}}/></span><small>{strength.label}</small></div><label>Confirm password<input type={showPassword ? 'text' : 'password'} autoComplete="new-password" placeholder="Re-enter password" value={confirm} aria-invalid={confirm.length > 0 && confirm !== password} onChange={(e) => { setConfirm(e.target.value); setError(''); }}/></label><label className="terms-row"><input type="checkbox" checked={terms} onChange={(e) => setTerms(e.target.checked)}/><span>I agree to Finova&apos;s terms for this demo account.</span></label>{feedback}<button type="submit" className="finova-login-primary" disabled={loading}>{loading ? <><Loader2 size={17} className="finova-spin"/> Creating account…</> : <>Create account <ArrowRight size={17}/></>}</button></form>}
    {step === 'success' && <div className="finova-login-step finova-login-success"><div className="finova-success-icon"><CheckCircle2 size={34}/></div><h3>{mode === 'signup' ? 'Account created' : 'Signed in'}</h3><p>{notice}</p><button type="button" className="finova-login-primary" onClick={onClose}>Continue to Finova <ArrowRight size={17}/></button></div>}
    {step !== 'chooser' && step !== 'success' && <button type="button" className="finova-login-secondary" onClick={() => setStep('chooser')}>Choose another option</button>}
  </section></div>;
}
