'use client';
import { Bell, ChevronDown, CircleHelp, Mail, Palette, ShieldCheck, UserRound, Wrench, X, Mic, Type } from 'lucide-react';
import { useEffect, useState, type ReactNode } from 'react';
import { useThemeSwitch } from '@/components/theme-toggle';
import { useEscape } from '@/lib/use-escape';
import { setInAppNotifications, useNotificationStore } from '@/components/notifications-panel';
import { AlertPreferences } from '@/components/alerts/alert-preferences';
import { useFinova } from '@/lib/data/store';
import { alertDemoWorkspace } from '@/lib/alerts/demo-scenario';
import { seedAccounts, seedEntries, seedExpenses, seedInvoices } from '@/lib/data/seed';
import { clearAlertState } from '@/lib/alerts/storage';
import { useSession } from '@/lib/demo-auth';
import { useWakeWordStatus, setWakeEnabled } from '@/lib/voice/wake-word';
import { useI18n } from '@/lib/i18n';

const supportEmail = process.env.NEXT_PUBLIC_SUPPORT_EMAIL || 'support@finova.example';
export function SettingsPanel({ onClose }: { onClose: () => void }) {
  const { isDark, toggle } = useThemeSwitch(); const [emailAlerts,setEmailAlerts] = useState(true); const [textSize,setTextSize] = useState<'standard'|'large'>((typeof window !== 'undefined' && localStorage.getItem('finova-text-size') as 'large'|'standard') || 'standard'); const {inApp:inAppAlerts}=useNotificationStore(); const replaceWorkspace=useFinova((s)=>s.replaceWorkspace); const {user}=useSession(); const wake=useWakeWordStatus(); const {t}=useI18n();
  useEscape(onClose);
  useEffect(()=>{try{setEmailAlerts(localStorage.getItem('finova:email-alerts:v1')!=='false')}catch{}},[]);
  useEffect(()=>{document.documentElement.dataset.textSize=textSize; localStorage.setItem('finova-text-size',textSize)},[textSize]);
  return <div className="support-overlay" role="presentation" onMouseDown={(e)=>{if(e.target===e.currentTarget)onClose()}}><section className="support-modal settings-modal" role="dialog" aria-modal="true" aria-labelledby="settings-title"><PanelHead eyebrow="FINOVA PREFERENCES" title="Settings" onClose={onClose}/><div className="settings-grid">
    <SettingsSection icon={<UserRound size={17}/>} title="Account" description="Your signed-in Finova identity."><div className="settings-account"><div className="settings-avatar">{user ? user.name.split(/\s+/).map((x)=>x[0]).join('').slice(0,2).toUpperCase() : '?'}</div><div><strong>{user?.name ?? 'Signed out'}</strong><span>{user?.email ?? 'No account is signed in.'}</span><small>{user?.role ?? 'Sign in to connect an account.'}</small></div></div></SettingsSection>
    <SettingsSection icon={<Palette size={17}/>} title="Appearance" description="Choose how Finova looks on this device."><ToggleRow label="Dark mode" description={isDark?'Dark theme is active':'Light theme is active'} checked={isDark} onChange={toggle}/><div className="text-size-control"><span><strong><Type size={15}/> Text size</strong><small>Increase interface text without changing browser zoom.</small></span><select value={textSize} onChange={(e)=>setTextSize(e.target.value as 'standard'|'large')}><option value="standard">Standard</option><option value="large">Large</option></select></div></SettingsSection>
    <SettingsSection icon={<Mic size={17}/>} title="Hands-free mode" description="Enable browser-based wake listening for voice commands."><ToggleRow label="Say 'Hi Finova'" description={wake.enabled ? (wake.listening?'Listening for the wake phrase.':'Hands-free mode is enabled.'):'Microphone is off until you enable this toggle.'} checked={wake.enabled} onChange={()=>setWakeEnabled(!wake.enabled)}/><p className="privacy-note">Voice wake uses your browser&apos;s speech-recognition engine. Depending on the browser, audio may be processed by the browser&apos;s speech service; Finova does not upload a wake recording itself.</p></SettingsSection>
    <SettingsSection icon={<Bell size={17}/>} title="Notifications" description="Control demo notification preferences on this device."><ToggleRow label="In-app notifications" description="Show updates in the notification panel" checked={inAppAlerts} onChange={()=>setInAppNotifications(!inAppAlerts)}/><ToggleRow label="Email notifications" description="Saved preference; delivery is not connected in this demo." checked={emailAlerts} onChange={()=>{setEmailAlerts(!emailAlerts);localStorage.setItem('finova:email-alerts:v1',String(!emailAlerts))}}/><AlertPreferences/><div className="alert-preferences"><button type="button" onClick={()=>{clearAlertState('demo-org','demo-user');replaceWorkspace(alertDemoWorkspace());window.location.reload()}}>Load alert demo</button><button type="button" onClick={()=>{clearAlertState('demo-org','demo-user');replaceWorkspace({accounts:seedAccounts,entries:seedEntries,invoices:seedInvoices,expenses:seedExpenses});window.location.reload()}}>Restore seed data</button></div></SettingsSection>
    <SettingsSection icon={<ShieldCheck size={17}/>} title="Security" description="Authentication status for this environment."><div className="security-note"><strong>Demo authentication</strong><span>Passwords are stored only as a salted digest for this local demo. Real sessions can use the QuikIT adapter when enabled.</span></div></SettingsSection>
  </div></section></div>;
}

const troubleshooting=['Refresh the page and try again if a module does not load correctly.','For sign-in problems, check the email address and password, then try again.','A journal entry must balance debits and credits before posting.','For visual issues, use the theme control in the sidebar or Settings.'];
const faqs=[['How do I record a transaction?','Open Transactions, create a journal entry, enter balanced debit and credit lines, then post it.'],['How do I create an invoice?','Open Invoices, choose New Invoice, add the customer and line items, then save the invoice.'],['Where can I review expenses?','Open Expenses to review recorded spending and inspect individual expense details.'],['How do I review financial reports?','Open Reports and choose the required statement and reporting period.'],['How do I change the theme?','Use the theme control in the sidebar or open Settings → Appearance.'],['How does hands-free mode work?','Enable the toggle in Settings, grant microphone permission, then say Hi Finova followed by a command.']];
export function HelpPanel({ onClose }: { onClose: () => void }) { const [openFaq,setOpenFaq]=useState<number|null>(0); useEscape(onClose); return <div className="support-overlay" role="presentation" onMouseDown={(e)=>{if(e.target===e.currentTarget)onClose()}}><section className="support-modal help-modal" role="dialog" aria-modal="true" aria-labelledby="help-title"><PanelHead eyebrow="FINOVA SUPPORT" title="Help & Support" onClose={onClose}/><div className="help-intro"><div className="help-intro-icon"><CircleHelp size={24}/></div><div><strong>How can we help?</strong><p>Find practical guidance for accounts, transactions, invoices, expenses, reports, and voice features.</p></div></div><div className="help-content"><div><h3>Frequently asked questions</h3><div className="faq-list">{faqs.map(([q,a],i)=><div key={q} className={`faq-item ${openFaq===i?'open':''}`}><button type="button" onClick={()=>setOpenFaq(openFaq===i?null:i)} aria-expanded={openFaq===i}><span>{q}</span><ChevronDown size={16}/></button>{openFaq===i&&<p>{a}</p>}</div>)}</div><h3 className="help-subhead"><Wrench size={14}/> Basic troubleshooting</h3><ul className="help-troubleshoot">{troubleshooting.map((x)=><li key={x}>{x}</li>)}</ul></div><aside className="support-contact"><h3>Support</h3><p>For assistance with this demo, contact the Finova support address.</p><a href={`mailto:${supportEmail}`}><Mail size={15}/> {supportEmail}</a><span>For service status and API documentation, use the Support centre.</span></aside></div></section></div>; }
function PanelHead({eyebrow,title,onClose}:{eyebrow:string;title:string;onClose:()=>void}){return <div className="support-head"><div><p className="eyebrow">{eyebrow}</p><h2 id={title==='Settings'?'settings-title':'help-title'}>{title}</h2></div><button type="button" className="modal-close" onClick={onClose} aria-label={`Close ${title}`}><X size={18}/></button></div>}
function SettingsSection({icon,title,description,children}:{icon:ReactNode;title:string;description:string;children:ReactNode}){return <section className="settings-section"><div className="settings-section-head"><span>{icon}</span><div><h3>{title}</h3><p>{description}</p></div></div><div className="settings-section-body">{children}</div></section>}
function ToggleRow({label,description,checked,onChange}:{label:string;description:string;checked:boolean;onChange:()=>void}){return <label className="toggle-row"><span><strong>{label}</strong><small>{description}</small></span><input type="checkbox" checked={checked} onChange={onChange}/><i aria-hidden="true"/></label>}
