export type Language = 'en' | 'hi' | 'hinglish';
export const LANGUAGES = [
  { code: 'en', nativeName: 'English', englishName: 'English' },
  { code: 'hi', nativeName: 'हिन्दी', englishName: 'Hindi' },
  { code: 'hinglish', nativeName: 'Hinglish', englishName: 'Hindi in Roman script' },
] as const;
export const messages = {
  en: {
    brand:{tagline:'Smarter books. Stronger business.'}, nav:{primary:'Primary navigation',secondary:'Secondary navigation',home:'Home',dashboard:'Dashboard',journal:'Transactions',invoices:'Invoices',expenses:'Expenses',reports:'Reports',accounts:'Chart of Accounts',forecast:'Cash Forecast',customers:'Customers',bank:'Banking',settings:'Settings',help:'Help & Support',light:'Light mode',dark:'Dark mode'},
    language:{title:'Language',appLanguage:'App language',manage:'Manage language',aiLanguage:'AI language',followDevice:'Follow device language',saved:'Language preference saved'},
    promo:{titleLine1:'Better finances',titleLine2:'Bigger clarity',body:'Track. Manage. Review.'},
    notifications:{label:'Notifications',unread:'unread'},
    account:{login:'Login',profileSettings:'Profile / Settings',switchAccount:'Switch account',signOut:'Sign out',account:'Account',signedOut:'Signed out',noAccount:'No account is signed in.',roleFallback:'Sign in to connect an account'},
    receipt:{scanLimit:'Free plan: 10 receipt scans per month.',fileTooLarge:'This file is too large. Choose a file up to 15 MB.',fileType:'That file type is not supported. Use JPG, PNG, WEBP or PDF.',ocrFailed:'Receipt scanning could not read this file. You can enter the expense manually.',pdfOcrFailed:'This PDF could not be read automatically. You can enter the expense manually.',cancelled:'Scanning was cancelled. Nothing was saved.',manual:'Enter manually',batchPremium:'Batch scanning is available with Premium.',extracted:'Receipt extracted. Review the highlighted fields before filing.',resolveValidation:'Resolve the validation warnings before confirming.',positiveTotal:'A positive total amount is required.'},
    assistant:{launcher:'Ask Finova AI',shortcutHint:'Open Finova AI · Ctrl/⌘ J',title:'Finova AI',subtitle:'A financial assistant grounded in your Finova records',input:'Ask about expenses, income, invoices or balances…',send:'Send question',mic:'Voice input',mute:'Mute spoken replies',speak:'Read replies aloud',clear:'Clear conversation',close:'Close Finova AI',review:'Answers use your Finova records. Verify figures before filing or legal use.',remaining:'{remaining} of {max} AI queries available',rateLimited:'You have reached the AI query limit. You can ask again in {seconds} s.',requestFailed:'The assistant could not be reached.',navigationComplete:'Done. The requested Finova view is open.',themeChanged:'Theme changed to {mode} mode.',languageChanged:'AI language updated.',autoDetect:'Auto-detect from my message',stopSpeaking:'Stop speaking'},
    voice:{unsupported:'Voice input requires a browser with speech recognition. You can continue by typing.',micBlocked:'Microphone access is blocked. Allow it for this site, then try again.',stopped:'The voice session stopped unexpectedly. Please try again or type your request.',didNotCatch:'I did not catch that. Please try again.',pause:'Pause listening',resume:'Resume listening',send:'Send voice command',cancel:'Cancel voice command',cancelled:'Cancelled. Nothing was changed.',confirmTitle:'Confirm action',confirmPrompt:'Please confirm this change.',confirm:'Confirm',handsFreeOff:'Hands-free mode is off',listening:'Listening for Hi Finova.',expenseAdded:'Added ₹{amount} expense for {vendor}.',invoicePaid:'{invoice} is marked as paid.',invoiceNotFound:'I could not identify that invoice, so nothing was changed.',invoiceDraftOpened:'The invoice draft screen is open. No invoice was sent or posted.',undone:'The last change was undone.'},
  },
  hi: {
    brand:{tagline:'बेहतर बहीखाते। मजबूत कारोबार।'}, nav:{primary:'मुख्य नेविगेशन',secondary:'द्वितीयक नेविगेशन',home:'होम',dashboard:'डैशबोर्ड',journal:'लेन-देन',invoices:'इनवॉइस',expenses:'खर्च',reports:'रिपोर्ट',accounts:'अकाउंट्स',forecast:'कैश पूर्वानुमान',customers:'ग्राहक',bank:'बैंकिंग',settings:'सेटिंग्स',help:'मदद और सहायता',light:'लाइट मोड',dark:'डार्क मोड'},
    language:{title:'भाषा',appLanguage:'ऐप भाषा',manage:'भाषा प्रबंधित करें',aiLanguage:'AI भाषा',followDevice:'डिवाइस की भाषा अपनाएँ',saved:'भाषा की पसंद सेव हो गई'},
    promo:{titleLine1:'बेहतर वित्त',titleLine2:'बेहतर स्पष्टता',body:'ट्रैक करें। प्रबंधित करें। समीक्षा करें।'},
    notifications:{label:'सूचनाएँ',unread:'अपठित'},
    account:{login:'लॉग इन',profileSettings:'प्रोफ़ाइल / सेटिंग्स',switchAccount:'खाता बदलें',signOut:'साइन आउट',account:'खाता',signedOut:'साइन आउट',noAccount:'कोई खाता साइन इन नहीं है।',roleFallback:'खाता जोड़ने के लिए साइन इन करें'},
    receipt:{scanLimit:'फ्री प्लान: हर महीने 10 रसीद स्कैन।',fileTooLarge:'यह फाइल बहुत बड़ी है। 15 MB तक की फाइल चुनें।',fileType:'यह फाइल प्रकार समर्थित नहीं है। JPG, PNG, WEBP या PDF चुनें।',ocrFailed:'रसीद को स्वचालित रूप से पढ़ा नहीं जा सका। आप खर्च मैन्युअल रूप से दर्ज कर सकते हैं।',pdfOcrFailed:'इस PDF को स्वचालित रूप से नहीं पढ़ा जा सका। आप खर्च मैन्युअल रूप से दर्ज कर सकते हैं।',cancelled:'स्कैन रद्द कर दिया गया। कुछ भी सेव नहीं हुआ।',manual:'मैन्युअल रूप से दर्ज करें',batchPremium:'एक साथ कई रसीद स्कैन करना Premium में उपलब्ध है।',extracted:'रसीद निकाली गई है। फाइल करने से पहले चिन्हित फ़ील्ड जांचें।',resolveValidation:'पुष्टि करने से पहले सत्यापन चेतावनियाँ ठीक करें।',positiveTotal:'कुल राशि शून्य से अधिक होनी चाहिए।'},
    assistant:{launcher:'Finova AI से पूछें',shortcutHint:'Finova AI खोलें · Ctrl/⌘ J',title:'Finova AI',subtitle:'आपके Finova रिकॉर्ड पर आधारित वित्तीय सहायक',input:'खर्च, आय, इनवॉइस या बकाये के बारे में पूछें…',send:'प्रश्न भेजें',mic:'आवाज़ से पूछें',mute:'बोले गए जवाब बंद करें',speak:'जवाब बोलकर सुनाएँ',clear:'बातचीत साफ़ करें',close:'Finova AI बंद करें',review:'जवाब आपके Finova रिकॉर्ड से आते हैं। फाइलिंग या कानूनी उपयोग से पहले आंकड़े जांच लें।',remaining:'{max} में से {remaining} AI प्रश्न उपलब्ध',rateLimited:'AI प्रश्नों की सीमा पूरी हो गई है। {seconds} सेकंड बाद फिर पूछें।',requestFailed:'सहायक तक पहुँचना संभव नहीं हुआ।',navigationComplete:'हो गया। मांगा गया Finova पेज खुल गया है।',themeChanged:'थीम {mode} मोड में बदल गई।',languageChanged:'AI भाषा अपडेट हो गई है।',autoDetect:'मेरे संदेश से भाषा पहचानें',stopSpeaking:'बोलना रोकें'},
    voice:{unsupported:'आवाज़ इनपुट के लिए speech recognition वाला ब्राउज़र चाहिए। आप टाइप कर सकते हैं।',micBlocked:'माइक्रोफ़ोन की अनुमति बंद है। इस साइट के लिए अनुमति देकर फिर प्रयास करें।',stopped:'आवाज़ सत्र अचानक रुक गया। फिर प्रयास करें या टाइप करें।',didNotCatch:'मैं समझ नहीं पाया। कृपया फिर बोलें।',pause:'सुनना रोकें',resume:'सुनना शुरू करें',send:'आवाज़ कमांड भेजें',cancel:'आवाज़ कमांड रद्द करें',cancelled:'रद्द किया गया। कोई बदलाव नहीं हुआ।',confirmTitle:'कार्रवाई की पुष्टि',confirmPrompt:'कृपया इस बदलाव की पुष्टि करें।',confirm:'पुष्टि करें',handsFreeOff:'हैंड्स-फ्री मोड बंद है',listening:'Hi Finova के लिए सुन रहा है।',expenseAdded:'{vendor} के लिए ₹{amount} का खर्च जोड़ा गया।',invoicePaid:'{invoice} को भुगतान किया हुआ चिह्नित किया गया है।',invoiceNotFound:'इस इनवॉइस की पहचान नहीं हो सकी, इसलिए कोई बदलाव नहीं किया गया।',invoiceDraftOpened:'इनवॉइस ड्राफ्ट स्क्रीन खुल गई है। कोई इनवॉइस भेजा या पोस्ट नहीं किया गया।',undone:'पिछला बदलाव वापस कर दिया गया है।'},
  },
  hinglish: {
    brand:{tagline:'Better books. Stronger business.'}, nav:{primary:'Primary navigation',secondary:'Secondary navigation',home:'Home',dashboard:'Dashboard',journal:'Transactions',invoices:'Invoices',expenses:'Kharch',reports:'Reports',accounts:'Accounts',forecast:'Cash Forecast',customers:'Customers',bank:'Banking',settings:'Settings',help:'Help & Support',light:'Light mode',dark:'Dark mode'},
    language:{title:'Language',appLanguage:'App language',manage:'Language manage karein',aiLanguage:'AI language',followDevice:'Device language follow karein',saved:'Language preference save ho gayi'},
    promo:{titleLine1:'Better finances',titleLine2:'Clearer decisions',body:'Track. Manage. Review.'},
    notifications:{label:'Notifications',unread:'unread'},
    account:{login:'Login',profileSettings:'Profile / Settings',switchAccount:'Switch account',signOut:'Sign out',account:'Account',signedOut:'Signed out',noAccount:'No account is signed in.',roleFallback:'Sign in to connect an account'},
    receipt:{scanLimit:'Free plan: har month 10 receipt scans.',fileTooLarge:'Ye file bahut badi hai. 15 MB tak ki file choose karein.',fileType:'Ye file type supported nahi hai. JPG, PNG, WEBP ya PDF choose karein.',ocrFailed:'Receipt automatically read nahi ho payi. Expense manually enter kar sakte hain.',pdfOcrFailed:'Is PDF ko automatically read nahi kiya ja saka. Expense manually enter kar sakte hain.',cancelled:'Scan cancel ho gaya. Kuch save nahi hua.',manual:'Manually enter karein',batchPremium:'Batch scanning Premium ke saath available hai.',extracted:'Receipt extract ho gayi hai. Filing se pehle highlighted fields check karein.',resolveValidation:'Confirm karne se pehle validation warnings resolve karein.',positiveTotal:'Total amount zero se zyada hona chahiye.'},
    assistant:{launcher:'Finova AI se poochhein',shortcutHint:'Finova AI kholein · Ctrl/⌘ J',title:'Finova AI',subtitle:'Aapke Finova records par based financial assistant',input:'Expense, income, invoice ya balance ke baare mein poochhein…',send:'Question bhejein',mic:'Voice input',mute:'Spoken replies mute karein',speak:'Reply bolkar sunayein',clear:'Conversation clear karein',close:'Finova AI band karein',review:'Answers aapke Finova records se aate hain. Filing ya legal use se pehle figures verify karein.',remaining:'{max} mein se {remaining} AI queries available',rateLimited:'AI query limit poori ho gayi hai. {seconds} s baad phir poochhein.',requestFailed:'Assistant tak nahi pahunch sake.',navigationComplete:'Done. Requested Finova view open hai.',themeChanged:'Theme {mode} mode mein change ho gayi.',languageChanged:'AI language update ho gayi.',autoDetect:'Mere message se language detect karein',stopSpeaking:'Bolna rokein'},
    voice:{unsupported:'Voice input ke liye speech recognition browser chahiye. Aap type kar sakte hain.',micBlocked:'Microphone access blocked hai. Site ke liye permission dekar dobara try karein.',stopped:'Voice session achanak ruk gaya. Dobara try karein ya type karein.',didNotCatch:'Main catch nahi kar paya. Dobara boliye.',pause:'Listening pause karein',resume:'Listening resume karein',send:'Voice command bhejein',cancel:'Voice command cancel karein',cancelled:'Cancel kar diya. Koi change nahi hua.',confirmTitle:'Action confirm karein',confirmPrompt:'Please is change ko confirm karein.',confirm:'Confirm',handsFreeOff:'Hands-free mode off hai',listening:'Hi Finova ke liye listening on hai.',expenseAdded:'{vendor} ke liye ₹{amount} ka expense add ho gaya.',invoicePaid:'{invoice} ko paid mark kar diya gaya hai.',invoiceNotFound:'Is invoice ko identify nahi kar paaye, isliye koi change nahi hua.',invoiceDraftOpened:'Invoice draft screen open hai. Koi invoice send ya post nahi hua.',undone:'Last change undo ho gaya.'},
  },
} as const;
export type MessageKey = keyof typeof messages.en;
