import { describe,it,expect } from 'vitest';
import { evaluateAlerts } from '@/lib/alerts/engine';
import { renderDigest } from '@/lib/alerts/digest';import { numberTokens } from '@/lib/alerts/explain';
import type { Workspace } from '@/lib/assistant/engine';
import { seedAccounts } from '@/lib/data/seed';
const NOW='2026-10-02';
const inv=(id:string,n:string,customer:string,due:string,total:number)=>({id,number:n,customer,date:'2026-09-01',dueDate:due,lines:[{id:`l-${id}`,description:'Service',quantity:'1',unitPrice:String(total)}],tax:0,discount:0,status:'Pending' as const,notes:''});
function withAlertScenario():Workspace{const invoices=[inv('a','INV-A','Apex Industries','2026-09-15',30000),inv('b','INV-B','BlueSky Retail','2026-09-20',10000),inv('c','INV-C','Nova Technologies','2026-09-25',8500),inv('d','INV-D','GreenLeaf Foods','2026-10-12',48000)];const expenses=[...Array.from({length:3},(_,i)=>({id:`SEP-${i}`,date:`2026-09-0${Math.min(i+1,2)}`,category:'Marketing',vendor:`Old ${i}`,description:'Campaign',amount:10000,paymentMethod:'Bank',status:'Paid' as const,notes:''})),...Array.from({length:3},(_,i)=>({id:`OCT-${i}`,date:`2026-10-0${Math.min(i+1,2)}`,category:'Marketing',vendor:`New ${i}`,description:'Campaign',amount:12200,paymentMethod:'Bank',status:'Paid' as const,notes:''}))];const invoiceEntries=invoices.map((i,n)=>({id:`INV-JE-${n}`,date:i.date,reference:i.number,description:'Invoice posting',status:'Posted' as const,source:'INVOICE' as const,sourceRef:i.id,lines:[{id:`ivd-${n}`,accountId:'1100',debit:i.lines[0]!.unitPrice?Number(i.lines[0]!.unitPrice):0,credit:0},{id:`ivc-${n}`,accountId:'4001',debit:0,credit:i.lines[0]!.unitPrice?Number(i.lines[0]!.unitPrice):0}]}));const entries=[...invoiceEntries,{id:'aug-in',date:'2026-08-10',reference:'A',description:'receipts',status:'Posted' as const,source:'MANUAL' as const,lines:[{id:'1',accountId:'1001',debit:10000,credit:0},{id:'2',accountId:'4001',debit:0,credit:10000}]},{id:'aug-out',date:'2026-08-20',reference:'B',description:'spend',status:'Posted' as const,source:'MANUAL' as const,lines:[{id:'3',accountId:'5001',debit:8000,credit:0},{id:'4',accountId:'1001',debit:0,credit:8000}]},{id:'sep-in',date:'2026-09-10',reference:'C',description:'receipts',status:'Posted' as const,source:'MANUAL' as const,lines:[{id:'5',accountId:'1001',debit:15000,credit:0},{id:'6',accountId:'4001',debit:0,credit:15000}]},{id:'sep-out',date:'2026-09-20',reference:'D',description:'spend',status:'Posted' as const,source:'MANUAL' as const,lines:[{id:'7',accountId:'5001',debit:8000,credit:0},{id:'8',accountId:'1001',debit:0,credit:8000}]}];return {accounts:seedAccounts,entries,invoices,expenses}}
describe('smart financial alerts',()=>{it('emits the four brief alert categories from a fixed scenario',()=>{const a=evaluateAlerts(withAlertScenario(),{now:NOW,config:{maxAlerts:20}});expect(a.some(x=>x.ruleId==='overdue-invoices')).toBe(true);expect(a.some(x=>x.ruleId==='expense-increase')).toBe(true);expect(a.some(x=>x.ruleId==='expected-receipts')).toBe(true);expect(a.some(x=>x.ruleId==='cash-flow-trend')).toBe(true)});it('never emits an empty why block',()=>{for(const a of evaluateAlerts(withAlertScenario(),{now:NOW,config:{maxAlerts:20}})){expect(a.why.whatHappened).toBeTruthy();expect(a.why.whyItMatters).toBeTruthy();expect(a.why.suggestedAction).toBeTruthy();expect(Object.keys(a.evidence.facts).length).toBeGreaterThan(0)}});it('keeps every numeric token traceable to evidence facts',()=>{for(const a of evaluateAlerts(withAlertScenario(),{now:NOW,config:{maxAlerts:20}})){const text=[a.title,a.summary,a.why.whatHappened,a.why.comparedWith||'',a.why.whyItMatters,a.why.suggestedAction].join(' ');const known=new Set(numberTokens(JSON.stringify(a.evidence.facts)));for(const token of numberTokens(text))expect(known.has(token)).toBe(true)}});it('renders an email-ready digest deterministically',()=>{const a=evaluateAlerts(withAlertScenario(),{now:NOW,config:{maxAlerts:20}});const d=renderDigest(a);expect(d.subject).toContain('Finova');expect(d.text).toContain(a[0]!.title);expect(d.html).toContain('<article>')});it('digest escapes hostile dynamic text',()=>{const a=evaluateAlerts(withAlertScenario(),{now:NOW,config:{maxAlerts:20}});const first=a[0]!;const x={...first,title:'<script>alert(1)</script>',why:{...first.why,whyItMatters:'<x>'}};expect(renderDigest([x]).html).not.toContain('<script>');expect(renderDigest([x]).html).toContain('&lt;script&gt;')})})
