'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {AlertTriangle,ArrowDownLeft,ArrowUpRight,Check,ChevronRight,CloudOff,Download,FileText,Link2,LockKeyhole,Plus,RefreshCw,Search,ShieldCheck,SlidersHorizontal,Trash2,Upload,X} from 'lucide-react';
import {FinanceModuleShell} from '@/components/finance-module-shell';
import {useBank} from '@/lib/bank/store';
import type {BankAccount,BankTransaction} from '@/lib/bank/types';
import {STATEMENT_MAX_DAYS,downloadStatementPdf,isoDaysAgo} from '@/lib/pdf/statement-pdf';

const money=(p:bigint)=>{const n=Number(p)/100;return `₹${new Intl.NumberFormat('en-IN',{maximumFractionDigits:2}).format(n)}`};
const date=(s:string)=>new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(s));
const statusTone=(s:string)=>s==='MATCHED'||s==='CATEGORISED'?'good':s==='NEEDS_ATTENTION'?'bad':s==='IGNORED'?'muted':'warn';

export function BankModule(){const b=useBank();const [tab,setTab]=useState<'review'|'accounts'|'rules'>('review');const [account,setAccount]=useState('');const [search,setSearch]=useState('');const [filter,setFilter]=useState<'all'|'unreviewed'|'attention'|'credit'|'debit'>('all');const [showConnect,setShowConnect]=useState(false);const [showRule,setShowRule]=useState(false);const [showStatement,setShowStatement]=useState(false);const input=useRef<HTMLInputElement>(null);
useEffect(()=>{b.seedSandbox();if(new URLSearchParams(window.location.search).get('statement')==='1')setShowStatement(true)},[]);
const rows=useMemo(()=>b.transactions.filter(t=>(!account||t.accountId===account)&&(!search||`${t.narration} ${t.merchant} ${t.category||''}`.toLowerCase().includes(search.toLowerCase()))&&(filter==='all'||(filter==='unreviewed'&&t.status==='UNREVIEWED')||(filter==='attention'&&t.status==='NEEDS_ATTENTION')||(filter==='credit'&&t.direction==='CREDIT')||(filter==='debit'&&t.direction==='DEBIT'))),[b.transactions,account,search,filter]);
const unreviewed=b.transactions.filter(t=>t.status==='UNREVIEWED');
const businessCash=b.transactions.reduce((s,t)=>s+(t.business?(t.direction==='CREDIT'?t.amountPaise:-t.amountPaise):0n),0n);
function exportCsv(){const lines=['Date,Merchant,Narration,Direction,Amount,Category,Status,Reference'];for(const t of rows)lines.push([t.date,`"${t.merchant.replaceAll('"','""')}"`,`"${t.narration.replaceAll('"','""')}"`,t.direction,money(t.amountPaise).replace('₹',''),t.category||'',t.status,t.reference||''].join(','));const blob=new Blob([lines.join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='finova-bank-transactions.csv';a.click();URL.revokeObjectURL(a.href)}
return <FinanceModuleShell active="bank"><div className="bank-page"><div className="bank-hero"><div><div className="eyebrow">Bank Integration</div><h1>Banking, imported and reconciled.</h1><p>Connect through consent-based Account Aggregator rails when enabled, or upload a statement without sharing bank credentials.</p></div><div className="bank-actions"><button className="secondary-button" onClick={()=>input.current?.click()}><Upload size={16}/> Upload statement</button><input ref={input} hidden type="file" accept=".csv,.xlsx,.xls,.pdf,.txt" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(!account){alert('Select a bank account first.');return;}const r=await b.importFile(f,account);alert(r.errors.length?r.errors.join('\n'):`Imported ${r.added} transactions; ${r.duplicates} duplicate(s) skipped.`);e.currentTarget.value=''}}/><button className="primary-button" onClick={()=>setShowConnect(true)}><Link2 size={16}/> Connect bank</button></div></div>
<div className="bank-trust"><ShieldCheck size={18}/><strong>Read-only by design</strong><span>Finova never asks for internet-banking passwords, PINs or OTPs.</span><LockKeyhole size={17}/><span>AA consent is purpose- and time-bound.</span></div>
<div className="bank-summary-grid"><Summary label="Connected accounts" value={String(b.accounts.length)}/><Summary label="To review" value={String(unreviewed.length)}/><Summary label="Business net imported" value={money(businessCash)} tone={businessCash>=0n?'good':'bad'}/><Summary label="Last sync" value={b.accounts.filter(a=>a.lastSyncedAt).sort((x,y)=>String(y.lastSyncedAt).localeCompare(String(x.lastSyncedAt)))[0]?.lastSyncedAt?date(String(b.accounts.find(a=>a.lastSyncedAt)?.lastSyncedAt)): 'Not synced'}/></div>
<div className="bank-tabs"><button className={tab==='review'?'active':''} onClick={()=>setTab('review')}>Review inbox <b>{unreviewed.length}</b></button><button className={tab==='accounts'?'active':''} onClick={()=>setTab('accounts')}>Accounts</button><button className={tab==='rules'?'active':''} onClick={()=>setTab('rules')}>Rules</button></div>
{tab==='review'&&<><div className="bank-toolbar"><div className="search-field"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search narration, merchant or category"/></div><select value={account} onChange={e=>setAccount(e.target.value)}><option value="">All accounts</option>{b.accounts.map(a=><option key={a.id} value={a.id}>{a.bankName} {a.maskedAccountNumber}</option>)}</select><select value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}><option value="all">All</option><option value="unreviewed">Needs review</option><option value="attention">Needs attention</option><option value="credit">Credits</option><option value="debit">Debits</option></select><button className="secondary-button" onClick={exportCsv}><Download size={15}/> Export</button><button className="secondary-button" onClick={()=>setShowStatement(true)}><FileText size={15}/> Statement PDF</button>{unreviewed.length>0&&<button className="primary-button" onClick={()=>b.bulkConfirm(unreviewed.map(x=>x.id))}><Check size={15}/> Confirm high-confidence</button>}</div>
<div className="bank-review-list">{rows.map(t=><TransactionRow key={t.id} t={t} onConfirm={()=>b.confirm(t.id)} onIgnore={()=>b.ignore(t.id)} onEdit={(patch)=>b.confirm(t.id,patch)}/>) }{!rows.length&&<EmptyBank onUpload={()=>input.current?.click()}/>}</div></>}
{tab==='accounts'&&<Accounts accounts={b.accounts} premium={b.premium} onConnect={()=>setShowConnect(true)} onDisconnect={b.disconnect}/>} 
{tab==='rules'&&<Rules rules={b.rules} premium={b.premium} onAdd={()=>setShowRule(true)}/>} 
<div className="bank-disclaimer">Imported transactions are bookkeeping suggestions until reviewed. Bank-source records remain immutable; corrections affect the bookkeeping layer only.</div></div>{showConnect&&<ConnectModal accounts={b.accounts} onClose={()=>setShowConnect(false)} onConnect={(id)=>{b.createConsent('Sandbox AA',id);setShowConnect(false)}}/>}{showStatement&&<StatementModal accounts={b.accounts} transactions={b.transactions} defaultAccount={account} onClose={()=>setShowStatement(false)}/>}{showRule&&<RuleModal onClose={()=>setShowRule(false)} onSave={r=>{b.addRule(r);setShowRule(false)}}/>}</FinanceModuleShell>}
function Summary({label,value,tone}:{label:string;value:string;tone?:string}){return <div className="bank-summary"><span>{label}</span><strong className={tone||''}>{value}</strong></div>}
function TransactionRow({t,onConfirm,onIgnore,onEdit}:{t:BankTransaction;onConfirm:()=>void;onIgnore:()=>void;onEdit:(p:Partial<BankTransaction>)=>void}){const [editing,setEditing]=useState(false);const [cat,setCat]=useState(t.category||'Other');return <article className="bank-tx"><div className={`bank-direction ${t.direction==='CREDIT'?'credit':'debit'}`}>{t.direction==='CREDIT'?<ArrowDownLeft size={17}/>:<ArrowUpRight size={17}/>}</div><div className="bank-tx-main"><div className="bank-tx-title"><strong>{t.merchant}</strong><span>{date(t.date)}</span><span className={`status-pill ${statusTone(t.status)}`}>{t.status.replace('_',' ')}</span></div><p>{t.narration}</p><div className="bank-suggestion">Suggested <strong>{t.category||'Other'}</strong> · {Math.round(t.confidence*100)}% confidence · {t.suggestionReason}</div>{t.invoiceIds.length>0&&<div className="bank-match"><Link2 size={14}/> Possible invoice match: {t.invoiceIds.join(', ')}</div>}{editing&&<div className="bank-inline"><label>Category<select value={cat} onChange={e=>setCat(e.target.value)}><option>Office Supplies</option><option>Travel</option><option>Meals</option><option>Utilities</option><option>Software & Subscriptions</option><option>Sales Receipt</option><option>Bank Charges</option><option>Other</option></select></label><button className="primary-button" onClick={()=>{onEdit({category:cat,confidence:1,suggestionReason:'User confirmed correction'});setEditing(false)}}>Save</button></div>}</div><div className="bank-tx-amount"><strong className={t.direction==='CREDIT'?'credit':'debit'}>{t.direction==='CREDIT'?'+':'-'}{money(t.amountPaise)}</strong>{t.status==='UNREVIEWED'&&<div className="bank-row-actions"><button title="Confirm" onClick={onConfirm}><Check size={16}/></button><button title="Change" onClick={()=>setEditing(v=>!v)}><SlidersHorizontal size={16}/></button><button title="Ignore" onClick={onIgnore}><X size={16}/></button></div>}</div></article>}
function EmptyBank({onUpload}:{onUpload:()=>void}){return <div className="bank-empty"><CloudOff size={32}/><h3>No transactions to review</h3><p>Upload a CSV, Excel or PDF statement, or connect a sandbox Account Aggregator account.</p><button className="primary-button" onClick={onUpload}><Upload size={15}/> Upload statement</button></div>}
function Accounts({accounts,premium,onConnect,onDisconnect}:{accounts:BankAccount[];premium:boolean;onConnect:()=>void;onDisconnect:(id:string)=>void}){return <div className="bank-account-grid">{accounts.map(a=><div className="bank-account-card" key={a.id}><div><ShieldCheck size={20}/><span className="status-pill good">{a.syncStatus}</span></div><h3>{a.bankName}</h3><p>{a.accountType} · {a.maskedAccountNumber}</p><strong>{money(a.balancePaise)}</strong><small>Balance as of {date(a.balanceDate)}</small><div className="account-meta"><span>Business use: {a.businessUse?'Yes':'No'}</span><span>Last synced: {a.lastSyncedAt?date(a.lastSyncedAt):'Never'}</span></div><div><button className="secondary-button" onClick={()=>onDisconnect(a.id)}><Trash2 size={14}/> Disconnect</button><button className="secondary-button"><RefreshCw size={14}/> Sync</button></div></div>)}<button className="bank-add-account" onClick={()=>{if(!premium&&accounts.length>=1){alert('Multiple connected accounts are a Premium feature.');return;}onConnect()}}><Plus size={22}/><strong>Connect another account</strong><span>AA or statement upload</span></button></div>}
function Rules({rules,premium,onAdd}:{rules:BankModuleRule[];premium:boolean;onAdd:()=>void}){return <section className="module-card"><div className="bank-section-head"><div><h2>Auto-categorisation rules</h2><p>Rules run before learned vendor mappings and classifier suggestions.</p></div><button className="primary-button" disabled={!premium} onClick={onAdd}><Plus size={15}/> {premium?'Add rule':'Premium: Add rule'}</button></div>{rules.map(r=><div className="rule-row" key={r.id}><div><strong>{r.name}</strong><span>{r.narrationContains?`Narration contains “${r.narrationContains}”`: 'All matching transactions'} → {r.category}</span></div><span className="status-pill good">{r.enabled?'Enabled':'Paused'}</span></div>)}{!premium&&<div className="premium-preview"><strong>Premium bank automation</strong><span>Auto-rules, invoice/receipt reconciliation, recurring detection, alerts and accountant access unlock with Premium.</span></div>}</section>}
type BankModuleRule=ReturnType<typeof useBank.getState>['rules'][number];
function ConnectModal({accounts,onClose,onConnect}:{accounts:BankAccount[];onClose:()=>void;onConnect:(id:string)=>void}){const [id,setId]=useState(accounts[0]?.id||'');return <div className="journal-overlay"><section className="journal-modal finance-modal bank-modal"><div className="modal-head"><div><div className="eyebrow">Secure connection</div><h2>Connect a bank account</h2></div><button className="modal-close" onClick={onClose}><X size={18}/></button></div><div className="consent-box"><ShieldCheck size={22}/><div><strong>Read-only, consent-based access</strong><p>Finova will request transaction and deposit-account data only for bookkeeping and cash-flow reconciliation. You approve the access with the AA/bank flow. Finova does not collect your bank password, PIN or OTP.</p></div></div><label>Account<select value={id} onChange={e=>setId(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.bankName} · {a.maskedAccountNumber}</option>)}</select></label><div className="consent-grid"><span>Data: transactions + account profile</span><span>Purpose: bookkeeping</span><span>History: up to 12 months</span><span>Access: time-bound / revocable</span></div><div className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" onClick={()=>onConnect(id)}><ShieldCheck size={15}/> Approve sandbox consent</button></div><small>Production AA connectivity requires Finova to complete applicable FIU onboarding, ReBIT/Sahamati certification and commercial agreements.</small></section></div>}
function RuleModal({onClose,onSave}:{onClose:()=>void;onSave:(r:Omit<BankModuleRule,'id'|'createdAt'>)=>void}){const [name,setName]=useState('');const [contains,setContains]=useState('');const [category,setCategory]=useState('Office Supplies');return <div className="journal-overlay"><section className="journal-modal finance-modal"><div className="modal-head"><h2>Add categorisation rule</h2><button className="modal-close" onClick={onClose}><X size={18}/></button></div><div className="form-grid"><label>Rule name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Office supplier rule"/></label><label>Narration contains<input value={contains} onChange={e=>setContains(e.target.value)} placeholder="ABC OFFICE"/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>Office Supplies</option><option>Travel</option><option>Meals</option><option>Utilities</option><option>Software & Subscriptions</option><option>Other</option></select></label></div><div className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={!name||!contains} onClick={()=>onSave({name,narrationContains:contains,category,enabled:true})}>Save rule</button></div></section></div>}

function StatementModal({accounts,transactions,defaultAccount,onClose}:{accounts:BankAccount[];transactions:BankTransaction[];defaultAccount:string;onClose:()=>void}){const min=isoDaysAgo(STATEMENT_MAX_DAYS);const max=isoDaysAgo(0);const qp=typeof window==='undefined'?new URLSearchParams():new URLSearchParams(window.location.search);const clampD=(v:string|null,d:string)=>v&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&v>=min&&v<=max?v:d;const [from,setFrom]=useState(clampD(qp.get('from'),min));const [to,setTo]=useState(clampD(qp.get('to'),max));const [acct,setAcct]=useState(defaultAccount);const [err,setErr]=useState('');const count=transactions.filter(t=>(!acct||t.accountId===acct)&&t.date.slice(0,10)>=from&&t.date.slice(0,10)<=to).length;
function go(){if(!from||!to){setErr('Choose both a start and an end date.');return}if(from>to){setErr('The start date cannot be after the end date.');return}if(from<min||to>max){setErr(`Statements can cover only the last ${STATEMENT_MAX_DAYS} days.`);return}downloadStatementPdf({transactions,accounts,accountId:acct,from,to});onClose()}
return <div className="journal-overlay"><section className="journal-modal finance-modal bank-modal" role="dialog" aria-modal="true" aria-label="Download statement"><div className="modal-head"><div><div className="eyebrow">Statement</div><h2>Download statement (PDF)</h2></div><button className="modal-close" onClick={onClose} aria-label="Close"><X size={18}/></button></div><p className="statement-hint">Choose a date range within the last {STATEMENT_MAX_DAYS} days.</p><div className="form-grid"><label>From<input type="date" value={from} min={min} max={to||max} onChange={e=>{setFrom(e.target.value);setErr('')}}/></label><label>To<input type="date" value={to} min={from||min} max={max} onChange={e=>{setTo(e.target.value);setErr('')}}/></label><label className="full">Account<select value={acct} onChange={e=>setAcct(e.target.value)}><option value="">All accounts</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.bankName} {a.maskedAccountNumber}</option>)}</select></label></div><div className="statement-count">{count} transaction{count===1?'':'s'} in this range</div>{err&&<div className="validation-error" role="alert">{err}</div>}<div className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" onClick={go}><Download size={15}/> Download PDF</button></div></section></div>}
